package com.autowave.enums;

import com.autowave.base.enums.MessageCode;
import com.autowave.base.enums.MessageType;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ErrorEnum implements MessageCode {
    GENERAL_ERROR("MESSAGE.GENERAL.M1", MessageType.ERROR),
    MANDATORY_FIELD("MESSAGE.GENERAL.M4", MessageType.ERROR),
    PASSWORDS_DIFFERENT("MESSAGE.USER.M2", MessageType.ERROR),
    PASSWORD_INVALID("MESSAGE.USER.M3", MessageType.ERROR),
    EMAIL_INVALID("MESSAGE.GENERAL.M5", MessageType.ERROR),
    EMAIL_EXISTS("MESSAGE.GENERAL.M6", MessageType.ERROR),
    LOGIN_EXISTS("MESSAGE.USER.M1", MessageType.ERROR),
    PASSWORD_MIN_LENGTH("MESSAGE.USER.M4", MessageType.ERROR),
    PASSWORD_NUM_LETTER("MESSAGE.USER.M5", MessageType.ERROR),
    NUMBER_PHONE_INVALID("MESSAGE.GENERAL.M7", MessageType.ERROR),
    BIRTH_DAY_IS_AFTER("MESSAGE.PATIENT.M1", MessageType.ERROR),
    CPF_EXIST("MESSAGE.GENERAL.M8", MessageType.ERROR),
    CPF_INVALID("MESSAGE.GENERAL.M9", MessageType.ERROR),
    CEP_INVALID("MESSAGE.PATIENT.M3", MessageType.ERROR),
    USER_HASH_INSTANCE("MESSAGE.EVOLUTION.M1", MessageType.ERROR),
    USER_NOT_HAVE_INSTANCE("MESSAGE.EVOLUTION.M2", MessageType.ERROR),
    YOU_NOT_HAVE_INSTANCE("MESSAGE.EVOLUTION.M3", MessageType.ERROR),
    CAMPAIGN_INVALID_SIZE("MESSAGE.CAMPAIGN.M1", MessageType.ERROR),
    CAMPAIGN_INVALID_DATE("MESSAGE.CAMPAIGN.M2", MessageType.ERROR),
    CAMPAIGN_TEMPLATE_INVALID("MESSAGE.CAMPAIGN.M3", MessageType.ERROR),
    CAMPAIGN_USER_INVALID("MESSAGE.CAMPAIGN.M4", MessageType.ERROR),
    CLIENT_NAME_INVALID("MESSAGE.CLIENT.M1", MessageType.ERROR),
    CLIENT_PHONE_INVALID("MESSAGE.CLIENT.M2", MessageType.ERROR),
    CLIENT_BIRTH_DATE_INVALID("MESSAGE.CLIENT.M3", MessageType.ERROR),
    CLIENT_LAST_PURCHASE_INVALID("MESSAGE.CLIENT.M4", MessageType.ERROR),
    CLIENT_USER_INVALID("MESSAGE.CLIENT.M5", MessageType.ERROR),
    PLAN_NAME_INVALID("MESSAGE.PLAN.M1", MessageType.ERROR),
    PLAN_PRICE_INVALID("MESSAGE.PLAN.M2", MessageType.ERROR),
    PLAN_BILLING_PERIOD_INVALID("MESSAGE.PLAN.M3", MessageType.ERROR),
    PLAN_FEATURES_INVALID("MESSAGE.PLAN.M4", MessageType.ERROR),
    SUBSCRIPTION_USER_INVALID("MESSAGE.SUBSCRIPTION.M1", MessageType.ERROR),
    SUBSCRIPTION_PLAN_INVALID("MESSAGE.SUBSCRIPTION.M2", MessageType.ERROR),
    SUBSCRIPTION_DATE_INVALID("MESSAGE.SUBSCRIPTION.M3", MessageType.ERROR),
    SUBSCRIPTION_STATUS_INVALID("MESSAGE.SUBSCRIPTION.M4", MessageType.ERROR),
    PAYMENT_SUBSCRIPTION_INVALID("MESSAGE.PAYMENT.M1", MessageType.ERROR),
    PAYMENT_AMOUNT_INVALID("MESSAGE.PAYMENT.M2", MessageType.ERROR),
    PAYMENT_STATUS_INVALID("MESSAGE.PAYMENT.M3", MessageType.ERROR),
    PAYMENT_DUPLICATED("MESSAGE.PAYMENT.M4", MessageType.ERROR),
    DISPATCH_CAMPAIGN_INVALID("MESSAGE.DISPATCH.M1", MessageType.ERROR),
    DISPATCH_CLIENT_INVALID("MESSAGE.DISPATCH.M2", MessageType.ERROR),
    DISPATCH_DATE_INVALID("MESSAGE.DISPATCH.M3", MessageType.ERROR),
    DISPATCH_STATUS_CONFLICT("MESSAGE.DISPATCH.M4", MessageType.ERROR),
    CAMPAIGN_DELETE_WITH_DISPATCH("MESSAGE.CAMPAIGN.M5", MessageType.ERROR),
    PLAN_DELETE_WITH_SUBSCRIPTION("MESSAGE.PLAN.M5", MessageType.ERROR),
    CLIENT_DELETE_WITH_CAMPAIGN("MESSAGE.CLIENT.M6", MessageType.ERROR),
    CLIENT_DELETE_WITH_DISPATCH("MESSAGE.CLIENT.M7", MessageType.ERROR),
    ;


    private final String code;
    private final MessageType type;
}
